project:
  type: website

website:
  title: "About Infertility"
  navbar:
    left:
      - href: index.qmd
        text: Home
  google-analytics: "G-WQXVTBHLMM"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
